apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: justsmartcontractsapidisk
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""